export const projectList = [
  {
    name: "Sitenote",
    tech: "React.js, Node.js ,MongoDB, Tailwind, shadcn/ui",
    imageUrl: "/images/sitenote.png",
    filter: "React.js,Node.js,MongoDB,Tailwind,firebase",
    href: "https://sitenote.in"
  },
  {
    name: "Discord Clone",
    tech: "Next.js, React.js, Shadcn, Typescript, Tailwind",
    imageUrl: "/images/discord-clone.webp",
    href: "https://github.com/venilsutariya/discord-clone",
    filter: "Next.js,Clerk,Shadcn,Typescript",
  },
  {
    name: "Spotify Clone",
    tech: "Next.js 13, React.js, Supabase, Typescript",
    imageUrl: "/images/spotify-clone.webp",
    href: "https://github.com/venilsutariya/spotify-clone",
    filter: "Next.js,Clerk,Supabase,Typescript",
  },
  {
    name: "Spark",
    tech: "Next.js 13, React.js, Tailwind, Clerk, Convex",
    imageUrl: "/images/spark.png",
    href: "https://github.com/venilsutariya/spark",
    filter: "Next.js,Tailwind,Clerk,Typescript",
  },
  {
    name: "Messanger Clone",
    tech: "Next.js 13, React.js, Tailwind, MongoDB",
    imageUrl: "/images/messanger.webp",
    href: "https://github.com/venilsutariya/messanger-clone",
    filter: "Next.js,Tailwind,Next Auth,Typescript",
  },
  {
    name: "Next Auth",
    tech: "Next.js 13, React.js, Tailwind, shadcn/ui",
    imageUrl: "/images/nextauth.png",
    href: "https://github.com/venilsutariya/Next-Auth",
    filter: "Next.js,Tailwind,Next Auth,Typescript",
  },
  {
    name: "BookmyBox",
    tech: "Nodejs, nodemailer, express, MongoDB",
    imageUrl: "/images/bookmybox.png",
    href: "https://github.com/venilsutariya/BookmyBoxbackend",
    filter: "Node.js,MongoDB,express,Typescript",
  },
  {
    name: "AI-SaaS image generator",
    tech: "React.js, Node.js ,Cloudinary",
    imageUrl: "/images/imaginify.png",
    href: "https://github.com/venilsutariya/AI-SaaS-Image-Generator",
    filter: "React.js,Node.js,MongoDB,Tailwind",
  },
  {
    name: "E-commerce",
    tech: "React.js, Node.js ,MongoDB, Tailwind",
    imageUrl: "/images/ecommerce.webp",
    href: "https://github.com/venilsutariya/E-commerce",
    filter: "React.js,Node.js,MongoDB",
  },
];
